mlrun/ce

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/override-full.yaml
- charts/mlrun-ce/templates/NOTES.txt
Signed-off-by: eliyahunoach77 <root@linux-eliyahun.iguaz.io>
> [mlrun-ce] update chart  grafana auth anonymous

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
- charts/mlrun-ce/values.yaml
Signed-off-by: eliyahunoach77 <root@linux-eliyahun.iguaz.io>
> [mlrun-ce] _bump nuclio

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/override-full.yaml
- charts/mlrun-ce/values.yaml
Signed-off-by: eliyahunoach77 <root@linux-eliyahun.iguaz.io>
> bump mlrun images

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/values.yaml
Signed-off-by: eliyahu77 <root@linux-eliyahun.iguaz.io>
> bump nuclio images

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/values.yaml
Signed-off-by: eliyahu77 <root@linux-eliyahun.iguaz.io>
> [mlrun-ce]bump mlrun

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/override-full.yaml
- charts/mlrun-ce/templates/_helpers.tpl
- charts/mlrun-ce/templates/config/mlrun-env-configmap.yaml
- charts/mlrun-ce/values.yaml
And Extra Env as additional env
> Use Common Env Config Map as Default Env

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/templates/NOTES.txt
- charts/mlrun-ce/values.yaml
* add NodePort Prometheus
* add persistence for grafana
> Add Prometheus NodePort and Grafana Persistency

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/values.yaml
https://jira.iguazeng.com/browse/CEML-37
> CEML-37 - Bump nuclio to 1.10.6

- charts/mlrun-ce/override-full.yaml
- charts/mlrun-ce/templates/config/mlrun-env-configmap.yaml
- charts/mlrun-ce/values.yaml
CE mode can be `lite`, `full` or empty.
https://jira.iguazeng.com/projects/CEML/issues/CEML-32
> CEML-32 - Add CE mode envvar

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/templates/config/mlrun-env-configmap.yaml
Added `MLRUN_CE__VERSION` to config so mlrun injects it in the client spec for the UI to display.
Updated `MLRUN_ARTIFACT_PATH` , `MLRUN_FEATURE_STORE__DATA_PREFIXES__DEFAULT` and `MLRUN_FEATURE_STORE__DATA_PREFIXES__NOSQL` as they are set in jupyter to align the configuration and also for them to `MLRUN_ARTIFACT_PATH` and `MLRUN_FEATURE_STORE__DATA_PREFIXES__DEFAULT` to be set in the client spec for the UI as well.
> MLRun Configs For Displaying Values in MLRun UI

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/templates/jupyter-notebook/deployment.yaml
- charts/mlrun-ce/templates/pipelines/deployments/metadata-envoy-deployment.yaml
- charts/mlrun-ce/templates/pipelines/deployments/metadata-grpc-deployment.yaml
- charts/mlrun-ce/templates/pipelines/deployments/metadata-writer.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-persistenceagent.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-scheduledworkflow.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-ui.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-viewer-crd.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-visualizationserver.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline.yaml
- charts/mlrun-ce/templates/pipelines/deployments/mysql.yaml
- charts/mlrun-ce/templates/pipelines/deployments/workflow-controller.yaml
- charts/mlrun-ce/values.yaml
add nodeselector and tolerations to pipeline and Jupiter
> add nodeselector and tolerations

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
> Bump MLRun Chart to 0.9.4

- charts/mlrun-ce/README.md
Leftovers from https://github.com/mlrun/ce/pull/58
> Fix README updates

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
see - https://github.com/v3io/helm-charts/pull/990
> Bump MLRun chart to fix PVC template

- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
> bump mlrun

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
update mlrun chart from `0.9.14` to `0.9.16`
> [mlrun] bump mlrun chart ver to 0.9.16

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/templates/config/mlrun-env-configmap.yaml
[ML-4894](https://jira.iguazeng.com/browse/ML-4894)
> Override Grafana URL in mlrun config

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/templates/pipelines/deployments/ml-pipeline-viewer-crd.yaml
- charts/mlrun-ce/values.yaml
this PR change mlrun default version to 1.6.1 for mlrun-ui, mlrun-api and jupyter client
> [FIX] Change mlrun version to 1.6.1

- charts/mlrun-ce/Chart.yaml
- tests/package.sh
For use in lab on-prem deployments
> Add package target to Makefile

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/requirements.lock
- charts/mlrun-ce/requirements.yaml
take latest fixes of mlrun chart and nuclio charts
> [Charts] Bump versions

- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/values.yaml
https://iguazio.atlassian.net/browse/ML-6096
> [FIX] Enable log collector by default and set the image tag to 1.6.1

- .github/workflows/ci.yaml
- Makefile
- charts/mlrun-ce/Chart.yaml
- charts/mlrun-ce/values.yaml
Added github action to lint charts (no only the yaml correctness)
> [CI] Lint helm charts
